### PR TITLE
Release v0.2.5

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by edg2s** [comment]
Merge after #50

**Comment by edg2s** [comment]
> We drop the GitHub PR number crap from commit names in changelogs. Otherwise good to go.

Aren't they useful?

**Comment by jdforrester** [comment]
> > We drop the GitHub PR number crap from commit names in changelogs. Otherwise good to go.
> 
> Aren't they useful?

Marginally, but mostly they're cruft.

**Comment by edg2s** [comment]
While reading the release notes on GitHub, they take you directly to the PR/issue

**Comment by jdforrester** [comment]
If they're so needed, you should add them to the three lines that lack them, then. :-)

**Comment by edg2s** [comment]
I don't mind, just merge either way

**Pull request merged**
