### PR TITLE
Setup basic plugin infrastructure and add 'msg-doc' rule

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by MatmaRex** [comment]
Could the plugin simply detect the bulleted lists in comments (`// * …`), which we already use, and drop the ugly 'msg:' prefix? I think that will be good enough for linting, and we already write comments for humans like "Messages used here:".

**Comment by edg2s** [comment]
Well a list could be anything, and we search quite broadly for comments. Adding msg: seems like quite a small amount of overhead to make it obvious what the comment is doing.

**Comment by MatmaRex** [comment]
As a human reading such a comment, I find it very confusing. The "msg" prefix seems to imply there might be other prefixes, and doesn't explain the purpose of the comment.

I'm not familiar with writing ESLint plugins, but I assumed it only looks at comments on lines preceding a `mw.msg( … )` (or similar) call?

**Comment by edg2s** [comment]
Comments are fetched by node, not line, so for nested calls we need to do a more advanced search. In:
```lang=js
$div
  // Comment
  .text( mw.msg(foo) )
```
no comments are considered to be "before" the me.msg call, so we need to do some traversal to find likely candidates.

Ultimately I think the lining error should point to some proper documentation on these comments as it will be difficult to make it self-documenting, but I think it should be reasonably structured and unique.

**Comment by edg2s** [comment]
This pattern could be used elsewhere where keys to a store are generated, e.g. icon usage in OOUI, in which case having a prefix would be useful to disambiguate.

That said it would be easy enough to change this rule in the future, so we could use plain lists for v1.

**Comment by edg2s** [comment]
I've dropped the 'msg:' requirement in this version, but I still think we will need it in the future.

A better example is constructed CSS classes:
```javascript
// The follow classes are used here:
// * ve-init-target-visual
// * ve-init-target-source
this.$element.addClass( 've-init-target-' + defaultMode );
```

**Comment by MatmaRex** [comment]
Neat!

**Pull request merged**
