### PR TITLE
Bump version to 0.2

### PR DESCRIPTION
**Pull request by jakobw**
* added `mediawiki/valid-package-file-require` rule

---

It would be great if we could get the new version released soon so we can install this package from npm and use the `mediawiki/valid-package-file-require` rule :)

### CODE REVIEW

**Comment by jdforrester** [comment]
@Ladsgroup, please don't merge releases like this. It's not signed, it doesn't create the changelog despite being the second release, and you don't have `npm publish` rights.

**Comment by Ladsgroup** [comment]
> @Ladsgroup, please don't merge releases like this. It's not signed, it doesn't create the changelog despite being the second release, and you don't have `npm publish` rights.

Sorry. There wasn't any changelog before so I thought it's fine. I should make one now.
How can we sign this?
Who has npm publish rights?

**Comment by jdforrester** [comment]
I do and so does Ed, the exact same as all the other linting tools we master in GitHub. When you're not used to a repo, ask first. :-)

**Comment by jdforrester** [comment]
Finish-up in #6

**Pull request merged**
