### PR TITLE
Use upath for Windows path normalization, add Windows to tests

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by edg2s** [comment]
Yeah they give an example of passing an array to `runs-on` but that's for something else.

**Comment by edg2s** [comment]
Looks like docgen on windows is failing...

**Comment by jdforrester** [comment]
Given you're renaming the jobs, we'll have to adjust the repo config for which of these need to pass to allow merging, BTW.

**Comment by edg2s** [comment]
> Given you're renaming the jobs, we'll have to adjust the repo config for which of these need to pass to allow merging, BTW.

Done

**Pull request merged**
